Servers:
  1: 
    Address: 127.0.0.1
    Port: 1234
  2: 
    Address: 127.0.0.1
    Port: 1235
  3: 
    Address: 127.0.0.1
    Port: 1236
  4: 
    Address: 127.0.0.1
    Port: 1237
Timeout:
  Min_ms: 5000   # ok to use 5000 for development, but 150 more realistic
  Max_ms: 10000  # ok to use 10000 for development, but 300 more realistic
NVStateFilenameBase: raftstate